- name: Add Stack User (stack|stack)
  user: name=stack comment="Stack User" groups=wheel password=$6$rounds=656000$GxOkQlwGoe.LBYrK$tIFHEOC/mUNwvTxdqLJNNxSUOQmyaxILNswSh2itglm3104zfjJPs07JASsexLCng4T5ZrWPob4hQK8tlQuJx. state=present

- name: Change root pw (root|rpcr)
  user: name=root password=$6$rounds=656000$0tqH37pBAxrlG9H0$KLGmcdSUAkXbvbUq0VF.10FEnII6QEa9HTA6pdzlGg46voT5Wyl6u6eLckwyLuaDdf8ihW1r5aJYHVcLzmkiz.

- name: disable host checking
  lineinfile: dest=/etc/ssh/ssh_config line="   StrictHostKeyChecking no"

- name: Installing EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Enable epel
  lineinfile: dest=/etc/yum.repos.d/epel.repo regexp="^enabled=0" line="enabled=1" state=present

- name: Add some useful extra packages
  yum: name={{ item }} state=present
  with_items:
    - vim
    - vim-X11
    #- erlang-wx
# vim-X11 is added for gvimdiff

- name: Stop Network manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Change the default editor to the friendly vim
  lineinfile: dest=/etc/profile.d/editor.sh create=yes state=present line="export EDITOR=vim"

- name: install CentOS keys
  rpm_key: state=present key=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7

- name: Add OpenStack repository
  yum: name=centos-release-openstack-newton state=latest
  #yum: name=centos-release-openstack-mitaka state=latest

#- name: Apply all system updates
#  yum: name=* state=latest

- name: Install Packstack package
  yum: name=openstack-packstack state=present

- name: adds keystonerc to the bashrc of stack user
  lineinfile: dest=/home/stack/.bashrc insertafter=EOF line=". keystonerc_admin" state=present

- name: Allow Password Authentication through ssh
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication.*" state=present line="PasswordAuthentication yes"

- name: Restart SSH daemon
  service: name=sshd state=restarted

- name: remove old private keys
  file: path=/root/private state=absent

- name: remove old public keys
  file: path=/root/public state=absent

- name: remove old .ssh private keys
  file: path=/root/.ssh/id_rsa state=absent

- name: remove old .ssh public keys
  file: path=/root/.ssh/id_rsa.pub state=absent

- name: Ensuring /root/.ssh is there
  file: path=/root/.ssh state=directory

- name: get root private key
  get_url:
    url: https://raw.githubusercontent.com/rax-rpcr/multi-fix/master/keys/private
    dest: /root/private
    mode: 0600
    force: yes

- name: set root private key
  command: cp -f /root/private /root/.ssh/id_rsa
  #file: src=/root/private dest=/root/.ssh/id_rsa force=yes mode=0600 #doesn't overwrite dest file :broken:

- name: get public key
  get_url:
    url: https://raw.githubusercontent.com/rax-rpcr/multi-fix/master/keys/public
    dest: /root/public
    force: yes

- name: set root public key
  command: cp -f /root/public /root/.ssh/id_rsa.pub
  #file: src=/root/public dest=/root/.ssh/id_rsa.pub force=yes #doesn't overwrite dest file :broken:

- name: add @compute key to authorized_key
  authorized_key: user=root key=https://raw.githubusercontent.com/rax-rpcr/multi-fix/master/keys/public

- name: add @vagrant key to authorized_key
  authorized_key: user=vagrant key=https://raw.githubusercontent.com/rax-rpcr/multi-fix/master/keys/public

- name: Installing RDO Packstack on controller1
  command: packstack --install-host=192.168.56.10 --mariadb-install=y --os-glance-install=y --os-cinder-install=y --os-nova-install=y --os-neutron-install=y --os-ceilometer-install=y --os-gnocchi-install=y --os-client-install=y --os-swift-install=y --os-aodh-install=n --nagios-install=y --os-neutron-vpnaas-install=n --os-neutron-lbaas-install=n --neutron-fwaas=n --os-horizon-install=y --novacompute-privif=eth1 --novanetwork-privif=eth1 --novanetwork-pubif=eth0 --novanetwork-auto-assign-floating-ip=y --os-manila-install=n --os-heat-install=y --os-compute-hosts=192.168.56.10,192.168.56.20 --use-epel=y --provision-demo=y --novanetwork-pubif=eth0

- name: disable default httpd vhost
  command: mv /etc/httpd/conf.d/15-default.conf /etc/httpd/conf.d/15-default.conf.bak

- name: restart apache
  service: name=httpd state=reloaded

- name: add keystonerc to stack user
  command: cp /root/keystonerc_admin /home/stack/keystonerc_admin

- name: set the right permissions to the keystonerc_admin file
  file: path=/home/stack/keystonerc_admin owner=stack group=stack

- name: add keystonerc to bashrc of root
  lineinfile: dest=/root/.bashrc insertafter=EOF line=". keystonerc_admin" state=present

- name: fixing redis service
  lineinfile: dest=/etc/redis.conf regexp=^bind=192.168.56.10 line=bind=0.0.0.0

- name: restarting redis service
  service: name=redis state=restarted enabled=yes

- name: Apply all system updates
  yum: name=* state=latest

- name: 'Restarting host machine(s) (Shows errors - OK to ignore!)'
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
