- name: Add Stack User (stack|stack)
  user: name=stack comment="Stack User" groups=wheel password=$6$rounds=656000$GxOkQlwGoe.LBYrK$tIFHEOC/mUNwvTxdqLJNNxSUOQmyaxILNswSh2itglm3104zfjJPs07JASsexLCng4T5ZrWPob4hQK8tlQuJx. state=present

- name: Change root pw (root|rpcr)
  user: name=root password=$6$rounds=656000$0tqH37pBAxrlG9H0$KLGmcdSUAkXbvbUq0VF.10FEnII6QEa9HTA6pdzlGg46voT5Wyl6u6eLckwyLuaDdf8ihW1r5aJYHVcLzmkiz.

- name: Installing EPEL
  #command: rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Enable epel
  #    lineinfile: sed -i "s/enabled=0/enabled=1/g" /etc/yum.repos.d/epel.repo
  lineinfile: dest=/etc/yum.repos.d/epel.repo regexp="^enabled=0" line="enabled=1" state=present

- name: Add some useful extra packages
  yum: name={{ item }} state=present
  with_items:
    - vim
    - vim-X11
    - erlang-wx
    - sshpass
# vim-X11 is added for gvimdiff

- name: Stop Network manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Change the default editor to the friendly vim
  lineinfile: dest=/etc/profile.d/editor.sh create=yes state=present line="export EDITOR=vim"

- name: Add Newton repository
  yum: name=centos-release-openstack-newton state=latest

- name: Apply all system updates
  yum: name=* state=latest

- name: Allow Password Authentication through ssh
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication.*" state=present line="PasswordAuthentication yes"

- name: Restart SSH daemon
  service: name=sshd state=restarted

- name: add root@controller key
  command: sshpass -p rpcr ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@192.168.56.10

- name: add root@controller key
    #command: sshpass -p rpcr ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@192.168.56.20
  command: ssh root@192.168.56.10 "sshpass -p rpcr ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@192.168.56.20"

#- name: add compute to packstack
